[package]
name = "bruvbles/boundhitbox"
description = "A light weight Spatial Query bound hitbox."
version = "0.0.1"
author = ["bruvbles"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = ["src", "src/*", "wally.toml", "wally.lock", "default.project.json"]

[dependencies]
Signal = "sleitnick/signal@2.0.3"